---
- hosts: all
  become: true
  roles:
    - p-rep-pack
    - ansible-hardening
    - ansible-os-hardening
    - ansible-ssh-hardening
    - role-secure-docker-daemon
    - install-packages
    - disable-ipv6
    - ebs-automatic-nvme-mapping
    - mount-volumes
    - setup-app-block42
    - keystore
    - start-docker
    - wait-for-sync
    - rename-db
    - start-docker
