#- name: Copy service
#  template:
#    src: service.prep.j2
#    dest: /etc/systemd/system/prep.service
#  notify: systemctl
#
#- name: start
#  service: name=prep state=enable

- name: "Start node application via docker-compose"
  docker_compose:
    project_src: /home/ubuntu
    state: present

